#!/bin/bash
# © 2023 AymeN rachdi     <contact@aymenrachdi.xyz>


# Set default variables
QT_VERSION="${QT_VERSION:-5.15.2}"
QT_PATH="${QT_PATH:-/opt/Qt}"
QT_HOST="${QT_HOST:-linux}"
QT_TARGET="${QT_TARGET:-desktop}"
#QT_MODULES="${QT_MODULES:-qtcharts}"
QT_MODULES="${QT_MODULES:-qtcharts qtwebengine}"  # Added qtwebengine module
echo "Installing QT ${QT_VERSION}"
# Exit immediately if a command exits with a non-zero status
set -e

apt-get update
apt-get install python3 python3-pip -y
pip3 install aqtinstall
aqt install-qt ${QT_HOST} ${QT_TARGET} ${QT_VERSION} -O ${QT_PATH} -m ${QT_MODULES}
echo "Remember to export the following to your PATH: ${QT_PATH}/${QT_VERSION}/*/bin"
echo "export PATH=$(readlink -e ${QT_PATH}/${QT_VERSION}/*/bin/):PATH"
echo "Deploying systemd service "

#Installing extra mandatory dependencies and removing conflicts
    echo "Installing extra mandatory dependencies and removing conflicts"
    usermod -a -G dialout $USER
    apt-get remove modemmanager -y
    apt install gstreamer1.0-plugins-bad gstreamer1.0-libav gstreamer1.0-gl -y
    apt install libfuse2 -y
    apt install libxcb-xinerama0 libxkbcommon-x11-0 libxcb-cursor0 -y
    
#Deploying systemd service 
    systemctl daemon-reload
    systemctl enable seabot_qgc.service
    systemctl start seabot_qgc.service
    systemctl status seabot_qgc.service
echo "seabot_qgc debian package is installed successfully"
