#!/bin/sh
# © 2023 AymeN rachdi     <contact@aymenrachdi.xyz>





#copying host 
    cp /etc/hosts /etc/hosts.bak
    cp /home/hosts /etc
    cp /home/config/* /home/seabot/.config/QGroundControl.org/

#Deploying systemd service 
   systemctl daemon-reload
   systemctl enable seabot_qgc.service
   systemctl start seabot_qgc.service
   systemctl status seabot_qgc.service
   echo "seabot_qgc debian package is installed successfully"


