#!/usr/bin/env bash

# Set default variables
QT_VERSION="${QT_VERSION:-5.15.2}"
QT_PATH="${QT_PATH:-/opt/Qt}"
QT_HOST="${QT_HOST:-linux}"
QT_TARGET="${QT_TARGET:-desktop}"
QT_MODULES="${QT_MODULES:-qtcharts qtwebengine}"  # Added qtwebengine module

# Exit immediately if a command exits with a non-zero status
set -e

# Check if Qt is already installed
if command -v qmake &> /dev/null; then
    echo "Qt is already installed. Skipping installation."
    exit 0
fi

# Install Qt
apt-get update
apt-get install python3 python3-pip -y
pip3 install aqtinstall
aqt install-qt ${QT_HOST} ${QT_TARGET} ${QT_VERSION} -O ${QT_PATH} -m ${QT_MODULES}
echo "Remember to export the following to your PATH: ${QT_PATH}/${QT_VERSION}/*/bin"
echo "export PATH=$(readlink -e ${QT_PATH}/${QT_VERSION}/*/bin/):PATH"
